// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5ZzbNmaMKvkTY3YCSpIxw_0YmcJYlwDA',
    appId: '1:1097156908926:web:04bb683e26b502e67c452f',
    messagingSenderId: '1097156908926',
    projectId: 'ctb-wallet-d2e7f',
    authDomain: 'ctb-wallet-d2e7f.firebaseapp.com',
    storageBucket: 'ctb-wallet-d2e7f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzzahRlXpiwwZHKe530DIrTYRtc16oEqs',
    appId: '1:1097156908926:android:a4b3f2fbd7bbaf397c452f',
    messagingSenderId: '1097156908926',
    projectId: 'ctb-wallet-d2e7f',
    storageBucket: 'ctb-wallet-d2e7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1fFGDI45p2X5ihiDuWL_A-bB6Z47Lj2s',
    appId: '1:1097156908926:ios:45ca856bdafb38c17c452f',
    messagingSenderId: '1097156908926',
    projectId: 'ctb-wallet-d2e7f',
    storageBucket: 'ctb-wallet-d2e7f.appspot.com',
    iosBundleId: 'com.example.cryptoTrader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1fFGDI45p2X5ihiDuWL_A-bB6Z47Lj2s',
    appId: '1:1097156908926:ios:3b479a64321e07887c452f',
    messagingSenderId: '1097156908926',
    projectId: 'ctb-wallet-d2e7f',
    storageBucket: 'ctb-wallet-d2e7f.appspot.com',
    iosBundleId: 'com.example.cryptoTrader.RunnerTests',
  );
}
